version: '2'

services:
  tracker:
    image: 'detlearsom/opentracker'
    ports:
      - 6969:6969
      - 6969:6969/udp
    volumes:
      - ~/api_file_server/opentracker:/etc/opentracker
    hostname: tracker
    container_name: tracker
    networks:
      capture:
        ipv4_address: 172.16.238.22

  torrent_host:
    image: 'detlearsom/torrent-host'
    ports:
      - "9096:9096"
      - "31967:31967"
      - "31967:31967/udp"
    volumes: 
      - '$PWD/share:/var/lib'
      - '$PWD/downloads:/root/Downloads'
    command: /var/lib/torrentHost.sh $DURATION
    networks:
      capture:
        ipv4_address: 172.16.238.15


  torrent_client1:
    image: 'detlearsom/torrent-host'
    container_name: torrent_client1
    ports:
      - "9097:9097"
      - "31968:31968"
      - "31968:31968/udp"
#    command: /var/lib/torrentClient.sh
    command: sleep 1000
    volumes: 
      - '$PWD/client1-share:/var/lib/'
    networks:
      capture:
        ipv4_address: 172.16.238.20
    depends_on:
      - torrent_host


  tcpdump_torrent:
    image: 'detlearsom/tcpdump'
    command: not(ip6 or arp or (udp and (src port 5353 or src port 57621))) -v -w "/data/dump-130-torrent-host-${CAPTURETIME}-sc${SCENARIO}-$REPNUM.pcap"
    depends_on:
      - torrent_host
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:torrent_host"
    depends_on:
      - dummy

  tcpdump_client1:
    image: 'detlearsom/tcpdump'
    command: not(ip6 or arp or (udp and (src port 5353 or src port 57621))) -v -w "/data/dump-130-torrent-client1-${CAPTURETIME}-sc${SCENARIO}-$REPNUM.pcap"
    depends_on:
      - torrent_client1
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:torrent_client1"
    depends_on:
      - dummy




  dummy:
    image: 'alpine'
    networks:
      - capture
    depends_on:
      - torrent_host

networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
